language: node_js
node_js:
- stable
services:
- mongodb
- docker
install:
- yarn
script:
- yarn integration_test
- yarn unit_test
- yarn build
- docker build -t cspcope/cope_backend .
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  skip_cleanup: true
  provider: script
  script: docker push cspcope/cope_backend
  branch: master
env:
  global:
  - secure: quUhyOWLTUVIbddroFi51ntgx7ugnPg7kmuWDouIgpru5gElxQ7Sxca2g9s9u4g1+s9Y3WDAv0ciantObNyhQa7Ci4HYRWtPHA9Uc0SJVCWRc0GxQiLb47JxZ3YAKr5rY1NfoU1rJEF85vq4j4n3fO4KyneAuRt2uH8vns61tHX65ubM5hplQCRZ2WE1xVmChud/2qTkWF+4pjPBs2pfXlP1wN2sz6FhzOEmYmPvjGngo0SHeGeOTNrYV/+qOth8g/SLS9+WgnHUCCDzyQxDO+ULa1LyDg0Cc1jjEj3igYtQkihmdVJBod6RAEk3RTZXD6gi6KrkFswBGBKXY3SQcF8cRqVt+XFYPsuSrF6RfEattF0dPmr5t3BEky2TbHllmJ+voi/wF20tlVPqMrsZ0LelTFjHfXA8F7Lx9bUIZI3Xnq/qS5mj1PTIWvqRVZYkBysqVa7KhOQEa1bhgfGERtBqnBltHkBrujN/DHTFPzRw3hLrKlx5mfMlU23vLAMDxiEfHAKNjhSIbTVs7Nb8Jd4i4H/pWPjo89bz0Lqu9IrOtrSBKprNkYrHahQPRcbqJRuL1tFMYVgILo5/81HBygjBqW58EtRVBl5yfM4bYnEWod6V15yC23xLeme8lGP2MuPCWUkWS8RNJB8Y9b40hO8cBi5RCDbwH6SSV24btpc=
  - secure: by7gqBZ5b31CIAAUETYw6HmbkHkQ1cJAYcJY9S28EfNiE0bVGr1Qgosu1LiIV1JpjLZpC6x6U7rrhCpUIkpUbUwi/rWEzm+ANd/Zx/K2wQLt8ISehjyCkajcY0AgKI21EL/zxp5E4TN8t1GqNALEzQurQlvyK2JX8Bh4lDPyWSQvPr+GkuZ2Mee4t+dGT1zkUbveq2ZOhU1zoDQ8tR1WHqkujj8Y53hUdN7DTyrOFPXvVONAM9+vVin7cqFDggzUg6Gw5xK4HGS1N0c+RUHbKJ3XU16MQolnthC/q81rKOG/Nx04lqrBjqqtWcGSVGjO1GBCFuslR8dIDBUGSOPC1ZWpnYZTm+P8oLaiVeFEo3e6578gy5BvgimpFiPL6Im9Gtu9hUE49Oj/o7lGhCfjWJnBENMzK1bifCNccs9fGYfBGp/7um84/NQdUv2oU9eKs/G8+DuVbUyLu2vzfSbxwHH11jYbSWM+XlqWuaU2TvsaEv34eXR8nQXS06wZmy2my6k3fViuxOE+txMhV2yqTnyeRiNNXREHzZZsPnIpX4ySojRiuarW0hEesYclC//f4uHNejR8rEMRk825yqZ+FIdTMFnlMnjPndlpR1pwhZ1ddJ3vA0gvdYsm6u+KvBy5dpFPybr2gNWNAmL2JSu4Zj8yTRvDBl8RX3Xcy1cXZXg=
