language: node_js
node_js:
- stable
services:
- mongodb
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
- yarn
script:
- yarn integration_test
- yarn unit_test
- yarn build
- docker build -t cspcope/cope_backend .
deploy:
  skip_cleanup: true
  provider: script
  script: docker push cspcope/cope_backend
  branch: master
env:
  global:
  - secure: quUhyOWLTUVIbddroFi51ntgx7ugnPg7kmuWDouIgpru5gElxQ7Sxca2g9s9u4g1+s9Y3WDAv0ciantObNyhQa7Ci4HYRWtPHA9Uc0SJVCWRc0GxQiLb47JxZ3YAKr5rY1NfoU1rJEF85vq4j4n3fO4KyneAuRt2uH8vns61tHX65ubM5hplQCRZ2WE1xVmChud/2qTkWF+4pjPBs2pfXlP1wN2sz6FhzOEmYmPvjGngo0SHeGeOTNrYV/+qOth8g/SLS9+WgnHUCCDzyQxDO+ULa1LyDg0Cc1jjEj3igYtQkihmdVJBod6RAEk3RTZXD6gi6KrkFswBGBKXY3SQcF8cRqVt+XFYPsuSrF6RfEattF0dPmr5t3BEky2TbHllmJ+voi/wF20tlVPqMrsZ0LelTFjHfXA8F7Lx9bUIZI3Xnq/qS5mj1PTIWvqRVZYkBysqVa7KhOQEa1bhgfGERtBqnBltHkBrujN/DHTFPzRw3hLrKlx5mfMlU23vLAMDxiEfHAKNjhSIbTVs7Nb8Jd4i4H/pWPjo89bz0Lqu9IrOtrSBKprNkYrHahQPRcbqJRuL1tFMYVgILo5/81HBygjBqW58EtRVBl5yfM4bYnEWod6V15yC23xLeme8lGP2MuPCWUkWS8RNJB8Y9b40hO8cBi5RCDbwH6SSV24btpc=
  - secure: XIyPnmOd9ox9SKoS+Xy/R0S5aPRcFaW7a0l7Z6Y3AZkp9tF2q0Yuw+cOHWtwPbJqyDKEdv1jSxLZ00Zmz3IXSfeKxWIvST9dr4sL5owbgLYAzbeAwN5pVE3CfHRnO5KwdnhOOZlpzs9JaVd3aJr1ZxH3r3Z8m4UIklze3jx6369vrFLoZKGhxQktrK/t/LXY2gLTrMf3Y+Xf3deGGpZwpBHLULnby3oPGXBf8tEpfry8GN1KhCByz4SrJVa1m10YiBaXpDJcUczFmIcGTtInyOY735kLOgPZjN+nFFRnHOUWQe2NpJzZL2VlHGmJGlk/xlEltKLwhbSOqdIxnJz+5MJ5VUTSy9vBxitWAjzWI9A5UITn8VtXQuGBzHmyP//Tyc4RrNHG1VUQ/cwhQ32SNPK+viO5OBlYhWq3drir0oEYAkgIuGYxAYqM/jmkFmJf1IdLY4VKScXmfX356Ms6Z0bbaupmfi1j1VnkEMcZH5Cr80wP0gxkV+OMS3nJ5tsGHngVSwrk5S/n6/RGuVrL1bWJq2THNlmBVFFkgGdHChYTF4mlC6Mhq9DgE6Ir492jpxHALNgMtIokg/sj+VMRLldgpSDrIkd+QHdL5k58oX2nWG4rNLStH/8AEDP62qomMIm0egbsoKfZaUOWW61JxSVguqBHNUDjrdQbSPh4LgE=
