version: "3"
services:
    web:
        image: copeteam/cope_backend
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "3000:3000"
        networks:
            - webnet
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
networks:
    webnet: